networks:
  caddy-internal:
    name: caddy-internal
    external: true

services:
  router-sync:
    container_name: router-sync
    image: ghcr.io/laforcem/router-sync:latest
    restart: always
    environment:
      ROUTER_HOST: 192.168.10.1
      ROUTER_USER: malc
      SSH_PRIVATE_KEY: ${SSH_PRIVATE_KEY}
      AGH_URL: http://adguard-home
      AGH_USER: router-sync
      AGH_PASSWORD: ${AGH_PASSWORD}
      SYNC_INTERVAL_MINUTES: 10
    networks:
      - caddy-internal
    volumes:
      - ./known_hosts:/root/.ssh/known_hosts:ro
