app:
  log_level: info
  mfa_provider: webui
  password_providers: [webui]
  webui_port: 2011
  watch_with_interval: 86400

all_users:
  xmp_sidecar: true
  notification_forwarder: true
  session_expiry_warning_days: 7

users:
  - username_file: /run/secrets/apple_id_malc
    directory: /data/malc
    cookie_directory: /home/icloudpd/.pyicloud/malc
  - username_file: /run/secrets/apple_id_grug
    directory: /data/grug
    cookie_directory: /home/icloudpd/.pyicloud/grug
