apiVersion: apps/v1
kind: Deployment
metadata:
  name: volsync
spec:
  template:
    spec:
      containers:
        - name: manager
          env:
            - name: TZ
              value: America/Denver
          volumeMounts:
            - name: zoneinfo
              mountPath: /usr/share/zoneinfo
              readOnly: true
      volumes:
        - name: zoneinfo
          hostPath:
            path: /usr/share/zoneinfo
            type: Directory
