apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actual-mcp
  namespace: actual
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: actual-mcp
    template:
      data:
        MCP_BRIDGE_PUBLIC_HOST: "budget.{{ .domain }}"
        ACTUAL_PASSWORD: "{{ .password }}"
        ACTUAL_BUDGET_SYNC_ID: "{{ .syncId }}"
        MCP_SSE_AUTHORIZATION: "{{ .sseAuth }}"
  data:
    - secretKey: password
      remoteRef:
        key: f7101051-f052-4f4f-8c11-b4cf01582bbc
    - secretKey: syncId
      remoteRef:
        key: 93066b6e-5a0e-46bc-8bfb-b4cf01586f87
    - secretKey: sseAuth
      remoteRef:
        key: 88668fd6-dd3a-41fc-ba9e-b4cf01590732
    - secretKey: domain
      remoteRef:
        key: 4d3bfd3c-0a5d-496e-8eeb-b4ab00128f57