apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: restic-config
  namespace: actual
spec:
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: restic-config
    template:
      data:
        RESTIC_REPOSITORY: "rclone:dropbox:Homelab/backups/actual"
        RESTIC_PASSWORD: "{{ .resticPassword }}"
        RCLONE_CONFIG_DROPBOX_TYPE: "dropbox"
        RCLONE_CONFIG_DROPBOX_TOKEN: "{{ .dropboxToken }}"
  data:
    - secretKey: resticPassword
      remoteRef:
        key: 72650af4-6a33-4bef-baa8-b4cf0131846d
    - secretKey: dropboxToken
      remoteRef:
        key: 33a81225-97aa-4c31-a7f4-b4cf0131ad5b