http:
  routers:
    vm101-dashboard:
      entryPoints:
        - websecure
      rule: Host(`proxy.vm101.{{ env "DOMAIN"}}`)
      service: api@internal
      tls:
        certResolver: letsencrypt
      middlewares:
        - myauth
  middlewares:
    myauth:
      basicauth:
        users:
          - '{{ env "HTTP_BASIC_USER" }}:{{ env "HTTP_BASIC_PWD" }}'
