services:
  redbot:
    container_name: redbot
    image: phasecorex/red-discordbot
    restart: unless-stopped
    volumes:
      - ./redbot:/data
    environment:
      - TOKEN=${TOKEN}
      - PREFIX=.
      - TZ=America/Denver
      - PUID=1000
      - EXTRA_ARGS=--debug
