networks:
  traefiknet:
    name: traefiknet
    external: true

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.20.0
    container_name: audiobookshelf
    volumes:
      - /mnt/smb/audiobooks:/audiobooks
      - ./config:/config
      - ./metadata:/metadata
    labels:
      - traefik.enable=true
      - traefik.http.routers.audiobookshelf.rule=Host(`audiobooks.lan`)
      - traefik.http.routers.audiobookshelf.entrypoints=web
    environment:
      - TZ=America/Denver
    networks:
      - traefiknet
    sysctls:
      # Fix DNS problems/container Internet access
      net.ipv6.conf.all.disable_ipv6: 1
