services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.17.5
    ports:
      - 13378:80
    volumes:
      - ./audiobooks:/audiobooks
      - ./podcasts:/podcasts
      - ./config:/config
      - ./metadata:/metadata
    environment:
      - TZ=America/Denver
