services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.20.0
    container_name: audiobookshelf
    ports:
      - 13378:80
    volumes:
      - /mnt/smb/audiobooks:/audiobooks
      - ./config:/config
      - ./metadata:/metadata
    environment:
      - TZ=America/Denver
    sysctls:
      # Fix DNS problems/container Internet access
      net.ipv6.conf.all.disable_ipv6: 1
