name: audiobookshelf

networks:
  audiobookshelf-caddy:
    name: audiobookshelf-caddy

volumes:
  config:
  metadata:
  dropbox-audiobooks:
    driver: rclone
    driver_opts:
      remote: 'dropbox:Homelab/audiobookshelf/audiobooks'
      allow_other: 'true'
      vfs_cache_mode: full
      poll_interval: 60

services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:2.33.1
    container_name: audiobookshelf
    restart:
      unless-stopped
    networks:
      - audiobookshelf-caddy
    volumes:
      - dropbox-audiobooks:/audiobooks
      - config:/config
      - metadata:/metadata
    environment:
      - TZ=America/Denver
    sysctls:
      # Fix DNS problems/container Internet access
      net.ipv6.conf.all.disable_ipv6: 1
