name: caddy

volumes:
  data:
    name: caddy-mrgutsy_data
  config:
    name: caddy-mrgutsy_config

networks:
  actual-caddy:
    external: true
  audiobookshelf-caddy:
    external: true
  miniflux-caddy:
    external: true
  tandoor-caddy:
    external: true

services:
  caddy:
    build: ..
    container_name: caddy-mrgutsy
    environment:
      - DOMAIN
      - API_KEY
      - SECRET_KEY
      - EMAIL
      - TZ=America/Denver
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"  # HTTP for redirection
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - data:/data
      - config:/config
    networks:
      - actual-caddy
      - audiobookshelf-caddy
      - miniflux-caddy
      - tandoor-caddy
