services:
  mc:
    image: itzg/minecraft-server:java21
    container_name: paper
    environment:
      EULA: "true"
      TYPE: PAPER
      VIEW_DISTANCE: 10
      MEMORY: 2G
    ports:
      # Double-check port to ensure another server is not consuming it
      - "25520:25565"
    volumes:
      - mc-paper:/data
    restart: unless-stopped
volumes:
  mc-paper: {}