name: doco-cd

services:
  app:
    container_name: doco-cd
    image: ghcr.io/kimdre/doco-cd:0.109.2
    restart: unless-stopped
    environment:
      TZ: America/Denver
      DOCKER_HOST: tcp://docker-socket-proxy:2375
      POLL_CONFIG: |
        - url: https://github.com/laforcem/homelab.git
          reference: refs/heads/main
          interval: 300
          deployments:
            - name: doco-cd
              working_dir: doco-cd
              compose_files:
                - compose.yaml
    volumes:
      - data:/data
    cap_drop:
      - ALL
    depends_on:
      - docker-socket-proxy
    networks:
      - internal
    healthcheck:
      test: ["CMD", "/doco-cd", "healthcheck"]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3

  docker-socket-proxy:
    container_name: docker-proxy
    image: tecnativa/docker-socket-proxy:v0.5.0
    restart: unless-stopped
    cap_drop:
      - ALL
    environment:
      PING: 1
      VERSION: 1
      INFO: 1
      EVENTS: 1
      CONTAINERS: 1
      IMAGES: 1
      NETWORKS: 1
      VOLUMES: 1
      DISTRIBUTION: 1
      POST: 1
      AUTH: 0
      BUILD: 0
      COMMIT: 0
      EXEC: 0
      PLUGINS: 0
      SESSION: 0
      SWARM: 0
      SYSTEM: 0
      SERVICES: 0
      TASKS: 0
      NODES: 0
      SECRETS: 0
      CONFIGS: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal

volumes:
  data:

networks:
  internal:
