name: doco-cd

services:
  app:
    container_name: doco-cd
    image: ghcr.io/kimdre/doco-cd:0.109.2
    restart: unless-stopped
    environment:
      TZ: America/Denver
      DOCKER_HOST: tcp://docker-socket-proxy:2375
      SECRET_PROVIDER: bitwarden_sm
      SECRET_PROVIDER_ACCESS_TOKEN: ${SECRET_PROVIDER_ACCESS_TOKEN}
      POLL_CONFIG: |
        - url: https://github.com/laforcem/homelab.git
          reference: refs/heads/main
          interval: 300
          deployments:
            - name: doco-cd
              working_dir: doco-cd
              compose_files:
                - compose.yaml
              env_files:
                - /secrets/doco-cd.env
            - name: oci-backup
              working_dir: oci-backup
              compose_files:
                - compose.yaml
              external_secrets:
                OCI_CLI_USER: "fc755bbc-3ae9-4af5-8a12-b4ab000eef25"
                OCI_CLI_TENANCY: "4e09e83c-3749-48bf-a5e3-b4ab000f1c6d"
                OCI_CLI_KEY_CONTENT: "8a9a02f2-1883-4a25-bc75-b4ab00101cde"
                BOOT_VOLUME_ID: "4b5d7b03-572f-4859-b64a-b4ab00105cb1"
            - name: porkbun-ddns
              working_dir: porkbun-ddns
              compose_files:
                - compose.yaml
              external_secrets:
                DOMAIN: "4d3bfd3c-0a5d-496e-8eeb-b4ab00128f57"
                SUBDOMAIN: "40832d03-e0d3-49e6-80b8-b4ab00135d22"
                API_KEY: "05d378b9-de09-465c-80ec-b4ab001378de"
                SECRET_KEY: "e991c510-db7b-4e76-b885-b4ab00138c89"
    volumes:
      - data:/data
      - /opt/doco-cd-secrets:/secrets:ro
    cap_drop:
      - ALL
    depends_on:
      - docker-socket-proxy
    networks:
      - internal
    healthcheck:
      test: ["CMD", "/doco-cd", "healthcheck"]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3

  docker-socket-proxy:
    container_name: docker-proxy
    image: tecnativa/docker-socket-proxy:v0.5.0
    restart: unless-stopped
    cap_drop:
      - ALL
    environment:
      PING: 1
      VERSION: 1
      INFO: 1
      EVENTS: 1
      CONTAINERS: 1
      IMAGES: 1
      NETWORKS: 1
      VOLUMES: 1
      DISTRIBUTION: 1
      POST: 1
      AUTH: 0
      BUILD: 1
      COMMIT: 0
      EXEC: 1
      PLUGINS: 0
      SESSION: 1
      GRPC: 1
      SWARM: 0
      SYSTEM: 0
      SERVICES: 0
      TASKS: 0
      NODES: 0
      SECRETS: 0
      CONFIGS: 0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal

volumes:
  data:

networks:
  internal:
