networks:
  plex-caddy:
    name: plex-caddy

volumes:
  plex-config:
    name: plex-config

services:
  plex:
    image: plexinc/pms-docker:1.43.0.10492-121068a07
    container_name: plex
    # network_mode: host # https://archive.is/EWGoj
    restart: unless-stopped
    environment:
      - TZ=America/Denver
      - PLEX_CLAIM=${CLAIM_TOKEN}
      - ADVERTISEIP=https://plex.${DOMAIN}:443/
    networks:
      - plex-caddy
    volumes:
      - plex-config:/config
      - /mnt/lab:/data
