- name: Install qemu-guest-agent
  ansible.builtin.apt:
    name: qemu-guest-agent
    state: present
    update_cache: true

- name: Enable and start qemu-guest-agent
  ansible.builtin.systemd:
    name: qemu-guest-agent
    enabled: true
    state: started

- name: Install unattended-upgrades
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present

- name: Set timezone
  community.general.timezone:
    name: America/Denver

- name: Enable systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    enabled: true
    state: started
