apiVersion: 1
datasources:
  - name: InfluxDB
    uid: speedtest-influxdb
    type: influxdb
    access: proxy
    url: http://speedtest-influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: speedtest
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
