apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: airconnect-claim0
  name: airconnect-claim0
  namespace: airconnect
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
