- name: Configure all hosts
  hosts: all
  become: true
  roles:
    - common

- name: Configure utility host(s)
  hosts: utility
  become: true
  roles:
    - utility-services

- name: Configure secretary host
  hosts: secretary
  become: true
  roles:
    - secretary-network
