- name: Configure all hosts
  hosts: all
  become: true
  roles:
    - common

- name: Configure utility host(s)
  hosts: utility
  become: true
  roles:
    - utility-services

- name: Configure k3s node(s)
  hosts: k3s
  become: true
  roles:
    - k3s
