networks:
  caddy-internal:
    name: caddy-internal
    external: true

volumes:
  config:
  work:

services:
  adguard:
    container_name: adguard-home
    image: adguard/adguardhome:v0.107.73
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      # - "3000:3000/tcp" # used for first-time setup only
    networks:
      - caddy-internal
    volumes:
      - config:/opt/adguardhome/conf # config
      - work:/opt/adguardhome/work # working directory
