networks:
  traefiknet:
    name: traefiknet
    external: true

services:
  couchdb:
    image: couchdb:3 
    container_name: obsidian-livesync
    environment:
      - PUID=99
      - PGID=100
      - UMASK=0022
      - TZ=America/Denver
      - COUCHDB_USER=${COUCHDB_USERNAME}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ./couchdb/data:/opt/couchdb/data
      - ./couchdb/local.d:/opt/couchdb/etc/local.d
    restart: unless-stopped
    networks:
      - traefiknet
    labels:
      - traefik.enable=true
      - traefik.http.routers.obsidian-livesync.rule=Host(`obsidian-livesync.${DOMAIN}`)
      - traefik.http.routers.obsidian-livesync.entrypoints=websecure
      - traefik.http.routers.obsidian-livesync.tls.certresolver=myresolver
      - traefik.http.services.obsidian-livesync.loadbalancer.server.port=5984
