volumes:
  data:
  extensions:

services:
  freshrss:
    image: freshrss/freshrss:1.24.1
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
    volumes:
      - data:/var/www/FreshRSS/data
      - extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: America/Denver
      CRON_MIN: '3,33'
      TRUSTED_PROXY: 172.16.0.1/12 192.168.0.1/16
    labels:
      - traefik.enable=true
      - traefik.http.routers.freshrss.rule=Host(`rss.${DOMAIN}`)
      - traefik.http.routers.freshrss.entrypoints=websecure
      - traefik.http.routers.freshrss.tls.certresolver=myresolver
