services:
  drpp:
    container_name: drpp
    image: ghcr.io/phin05/discord-rich-presence-plex:latest
    restart: unless-stopped
    environment:
      DRPP_UID: 1000
      DRPP_GID: 1000
      DRPP_PLEX_SERVER_NAME_INPUT: Starcliff Lab
    volumes:
      - ./data:/app/data
      - /run/user/1000:/run/app