name: tandoor

services:
  db_recipes:
    container_name: tandoor-db
    restart: always
    image: postgres:16-alpine
    volumes:
      - postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - default

  web_recipes:
    container_name: tandoor-web
    restart: always
    image: vabene1111/recipes:2.5.3
    env_file:
      - ./.env
    volumes:
      - staticfiles:/opt/recipes/staticfiles
      - mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    networks:
      - tandoor-caddy
      - default

networks:
  default:
  tandoor-caddy:
    name: tandoor-caddy

volumes:
  staticfiles:
  postgresql:
  mediafiles:
