- name: Add Tailscale signing key
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/debian/trixie.noarmor.gpg
    dest: /usr/share/keyrings/tailscale-archive-keyring.gpg
    mode: "0644"

- name: Add Tailscale apt repository
  ansible.builtin.get_url:
    url: https://pkgs.tailscale.com/stable/debian/trixie.tailscale-keyring.list
    dest: /etc/apt/sources.list.d/tailscale.list
    mode: "0644"

- name: Install Tailscale
  ansible.builtin.apt:
    name: tailscale
    state: present
    update_cache: true

- name: Resolve Tailscale auth key
  ansible.builtin.set_fact:
    tailscale_authkey_resolved: "{{ tailscale_authkey }}"
  no_log: true

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    state: present
    reload: true

- name: Start Tailscale
  ansible.builtin.command:
    cmd: >-
      tailscale up
      --authkey={{ tailscale_authkey_resolved }}
      --advertise-routes=192.168.10.0/24,192.168.40.0/24
      --hostname=constrainer
