services:
  portainer_agent:
    image: portainer/agent:2.40.0-alpine
    container_name: portainer_agent
    restart: always
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
    healthcheck:
      test: ["CMD-SHELL", "timeout 10 nc -z -v 127.0.0.1 9001 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
